name: Bug Report
description: Report a bug to help us improve SAIF
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["jonathan-vella/1"]
assignees:
  - jonathan-vella
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        **Important**: If you've discovered a security vulnerability in SAIF that wasn't intentionally included for educational purposes, please report it responsibly.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running SAIF?
      options:
        - Azure (deployed via PowerShell script)
        - Azure (deployed via Deploy to Azure button)
        - Local Docker (docker-compose)
        - Local development (manual setup)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Web Frontend (PHP)
        - API Backend (Python/FastAPI)
        - Database (SQL Server)
        - Infrastructure (Bicep/ARM templates)
        - Deployment Scripts (PowerShell)
        - Documentation
        - Multiple components
        - Unknown/Not sure
    validations:
      required: true

  - type: checkboxes
    id: security-related
    attributes:
      label: Security Considerations
      description: Is this related to security?
      options:
        - label: This is an unintentional security vulnerability (not part of the educational challenges)
        - label: This affects one of the intentional security challenges
        - label: This is related to deployment security or infrastructure
        - label: Not security related

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: |
        Please provide relevant environment information:
        - Azure region (if deployed to Azure)
        - Browser version (for web frontend issues)
        - Docker version (for local development)
        - PowerShell version (for deployment issues)
      placeholder: |
        - Azure region: Sweden Central
        - Browser: Chrome 120.0.6099.109
        - Docker: 24.0.6
        - PowerShell: 7.3.8

  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: |
        If applicable, add screenshots, error logs, or other relevant information to help explain your problem.
        
        **Tip**: You can attach images by clicking this area to highlight it and then dragging files in.
      placeholder: Paste logs or drag screenshots here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...